/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 DrapePlant.gltf --transform -types
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useGesture } from "@use-gesture/react";
import { useThree } from "@react-three/fiber";
import { animated, useSpring } from "@react-spring/three";
import { useLocalStorage } from "react-use";
import { useEffect } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001: THREE.Mesh;
    Cylinder001_1: THREE.Mesh;
    Cylinder001_2: THREE.Mesh;
    Cylinder001_3: THREE.Mesh;
    Cylinder001_4: THREE.Mesh;
  };
  materials: {
    ["pot.002"]: THREE.MeshStandardMaterial;
    dirt: THREE.MeshStandardMaterial;
    ["metal.chrome"]: THREE.MeshStandardMaterial;
    ["plant.wood"]: THREE.MeshStandardMaterial;
    ["plant.leaf (image texture)"]: THREE.MeshStandardMaterial;
  };
};

export function DrapePlant(props: any) {
  const { nodes, materials } = useGLTF(
    "/DrapePlant-transformed.glb"
  ) as GLTFResult;

  const { staticScale, hoverScale, initialPosition } = props;

  const [position1, setPosition1] = useLocalStorage<number[]>(
    "drapePos1",
    initialPosition
  );

  const [position2, setPosition2] = useLocalStorage<number[]>("drapePos2");

  useEffect(() => {
    const position1FromStorage = JSON.parse(
      localStorage.getItem("drapePos1") ?? ""
    );
    setPosition2(
      position1FromStorage === "" ? initialPosition : position1FromStorage
    );
  }, []);

  const { size, viewport } = useThree();

  const aspect = size.width / viewport.width;

  const [spring, set] = useSpring(() => ({
    scale: staticScale,
    position: position1,
    rotation: [0, 0, 0],
    config: { friction: 13 },
  }));

  const bind = useGesture({
    onDrag: ({ offset: [x, y] }) => {
      const defaultPosition = position2 ? position2 : [0, 0, 0];
      const newPosition = [
        defaultPosition[0] + x / aspect,
        defaultPosition[1] - y / aspect,
        defaultPosition[2],
      ];

      set({ position: newPosition });
      setPosition1(newPosition);
    },
    onHover: ({ hovering }) =>
      set({ scale: hovering ? hoverScale : staticScale }),
  });

  return (
    <animated.group {...props} {...spring} {...bind()} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["pot.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_1.geometry}
        material={materials.dirt}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_2.geometry}
        material={materials["metal.chrome"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_3.geometry}
        material={materials["plant.wood"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001_4.geometry}
        material={materials["plant.leaf (image texture)"]}
      />
    </animated.group>
  );
}

useGLTF.preload("/DrapePlant-transformed.glb");
