/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 LilyOnStand.gltf --transform -types
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Circle_1: THREE.Mesh;
    Circle_2: THREE.Mesh;
    IVY_Curve004: THREE.Mesh;
    Plane005: THREE.Mesh;
    glass_panel: THREE.Mesh;
    glass_panel001: THREE.Mesh;
    stand: THREE.Mesh;
    vase: THREE.Mesh;
    ["Circle_-_stage_04_mirror_applied_and_sculpted"]: THREE.Mesh;
    HANDLE: THREE.Mesh;
    SUPPORT: THREE.Mesh;
  };
  materials: {
    Plant_Pot: THREE.MeshStandardMaterial;
    Plant_Soil: THREE.MeshStandardMaterial;
    Plant_Stem: THREE.MeshStandardMaterial;
    Plant_Leaf: THREE.MeshStandardMaterial;
    glass: THREE.MeshPhysicalMaterial;
    metal: THREE.MeshStandardMaterial;
  };
};

export function LilyOnStand(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/LilyOnStand-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.11, 0.14]} scale={0.16}>
        <group
          position={[0, 0, 0.03]}
          rotation={[Math.PI, 0, Math.PI]}
          scale={6.18}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_1.geometry}
            material={materials.Plant_Pot}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle_2.geometry}
            material={materials.Plant_Soil}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.IVY_Curve004.geometry}
          material={materials.Plant_Stem}
          scale={6.18}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials.Plant_Leaf}
          scale={6.18}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass_panel.geometry}
        material={materials.glass}
        position={[0, -0.28, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass_panel001.geometry}
        material={materials.glass}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stand.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.vase.geometry}
        material={materials.metal}
        position={[0, -0.11, 0.2]}
        scale={0.28}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes["Circle_-_stage_04_mirror_applied_and_sculpted"].geometry
          }
          material={materials.metal}
          position={[0.2, -0.09, -0.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HANDLE.geometry}
          material={materials.metal}
          position={[0, 0.31, -0.4]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.93}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SUPPORT.geometry}
          material={materials.metal}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/LilyOnStand-transformed.glb");
