/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 PaperPotFlower.gltf --transform --types
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useGesture } from "@use-gesture/react";
import { animated, useSpring } from "@react-spring/three";
import { useThree } from "@react-three/fiber";
import { useLocalStorage } from "react-use";
import { useEffect } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Tree005: THREE.Mesh;
    Tree005_1: THREE.Mesh;
    Tree005_2: THREE.Mesh;
    Cube: THREE.Mesh;
  };
  materials: {
    ["phlox stem"]: THREE.MeshStandardMaterial;
    ["phlox leaf"]: THREE.MeshStandardMaterial;
    ["phlox flower"]: THREE.MeshStandardMaterial;
    cardboard: THREE.MeshStandardMaterial;
  };
};

export function PaperPotFlower(props: any) {
  const { nodes, materials } = useGLTF(
    "/PaperPotFlower-transformed.glb"
  ) as GLTFResult;

  const { staticScale, hoverScale, initialPosition } = props;

  const [position1, setPosition1] = useLocalStorage<number[]>(
    "PaperPotPos1",
    initialPosition
  );

  const [position2, setPosition2] = useLocalStorage<number[]>("PaperPotPos2");

  useEffect(() => {
    const position1FromStorage = JSON.parse(
      localStorage.getItem("PaperPotPos1") ?? ""
    );
    setPosition2(
      position1FromStorage === "" ? initialPosition : position1FromStorage
    );
  }, []);

  const { size, viewport } = useThree();

  const aspect = size.width / viewport.width;

  const [spring, set] = useSpring(() => ({
    scale: staticScale,
    position: position1,
    rotation: [0, 0, 0],
    config: { friction: 13 },
  }));

  const bind = useGesture({
    onDrag: ({ offset: [x, y] }) => {
      const defaultPosition = position2 ? position2 : [0, 0, 0];
      const newPosition = [
        defaultPosition[0] + x / aspect,
        defaultPosition[1] - y / aspect,
        defaultPosition[2],
      ];

      set({ position: newPosition });
      setPosition1(newPosition);
    },
    onHover: ({ hovering }) =>
      set({ scale: hovering ? hoverScale : staticScale }),
  });

  return (
    <animated.group {...props} {...spring} {...bind()} dispose={null}>
      <group scale={0.59} rotation={[0, 3, 0]}>
        <group position={[0.05, 0.08, 0.1]} rotation={[-0.23, -0.53, 0.05]}>
          <mesh
            geometry={nodes.Tree005.geometry}
            material={materials["phlox stem"]}
          />
          <mesh
            geometry={nodes.Tree005_1.geometry}
            material={materials["phlox leaf"]}
          />
          <mesh
            geometry={nodes.Tree005_2.geometry}
            material={materials["phlox flower"]}
          />
        </group>
      </group>
      <mesh
        rotation={[0, 1, 0]}
        geometry={nodes.Cube.geometry}
        material={materials.cardboard}
      />
    </animated.group>
  );
}

useGLTF.preload("/PaperPotFlower-transformed.glb");
